apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jori-local
namePrefix: jori-local
nameSuffix: -v1

# Labels to add to all resources and selectors.
commonLabels:
  owner: jori
  app: jori-ap

# resources:
#   - ../../base/deployment.yaml
#   # - sub-dir/some-deployment.yaml
bases:
  - ../../base
