apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jori

# Labels to add to all resources and selectors.
commonLabels:
  owner: jori
  app: jori-ap

resources:
  - deployment.yaml
  - service.yaml
  - service-nodeport.yaml
